apiVersion: admiral.io/v1
kind: TrafficConfig
metadata:
  annotations:
    isDisabled: "false"
  labels:
    asset: httpbin
    env: qa
  name: httpbin-qa
  namespace: admiral
spec:
  edgeService:
    filters:
    - name: filter-17356028
    - name: filter-3387192
    routes:
    - config:
      - targetGroupSelector: Default
        targetSelector: qal--2037428113
      filterSelector: filter-3387192
      inbound: /health/full
      name: Health Check
      outbound: /health/full
      timeout: 5000
      workloadEnvSelectors:
      - qa
    - config:
      - targetGroupSelector: Default
        targetSelector: qal--2037428113
      filterSelector: filter-17356028
      inbound: /*
      name: v1
      outbound: /*
      timeout: 5000
      workloadEnvSelectors:
      - qa
    targetGroups:
    - name: DefaultGroup
      weights:
      - name: Default
        weight: 100
    targets:
    - meshDNS: sample.endpoint.mesh
      name: qal--2037428113
      port: 443
      socketTimeout: 5000
  quotaGroup:
    appQuotaGroups:
    - description: Total capacity of service
      name: Total Throttling Plan
      workloadEnvSelectors: 
      - qa
      quotas:
      - algorithm: scalable
        behaviour: softThrottle
        keyType: appIdOrToken
        maxAmount: 100
        name: Total
        rule: /*
        timePeriod: 1s
  workloadEnvs:
  - qa